steps:
  - name: ":node: Create bundle"
    commands:
      - "npm install"
      - "mkdir -p public"
      - "npm run build"
    artifact_paths: "public/*"

  - name: "save metadata"
    commands:
      - "buildkite-agent artifact download public/stats.json ."
      - "ls public"
      - "buildkite-agent meta-data set 'bundle-stats' < public/stats.json"

  - name: "report change"
    commands:
      - "npm install"
      - "./scripts/report_change"
