#!/bin/bash
set +e

export TOKEN="68d078ecd29d20f4a50c13f53c83a65ab12cc480"
export GITHUB_TOKEN="08d22354e4bc452d7cedeb28ddc68c110d18a542"

ANNOTATION="$(node ./scripts/report-change.js)"
if [ -n "$ANNOTATION" ]; then
  buildkite-agent annotate "$ANNOTATION" --style 'info'
fi

